### ISSUE TITLE
优化深色模式下代码高亮样式

### ISSUE THREAD

**Issue by forecho** [forecho/hugo-theme-echo#1]

**Comment by forecho** [comment]
目前比较好的方案就是选用深色模式的代码高亮主题 [Chroma Style Gallery](https://xyproto.github.io/splash/docs/all.html)

**Comment by wubh2012** [comment]
请问怎么修改代码的高亮主题呢

**Comment by whuwangyong** [comment]
深色模式对比度太强烈了。黑色背景太黑，白字太白，亮瞎眼~可以参考下[这个主题](https://chirpy.cotes.page/)的深色模式。

**Comment by forecho** [comment]
不错的建议

**Comment by forecho** [comment]
https://github.com/forecho/hugo-theme-echo/commit/860fe1d4b9e8d10ec1becc1ceedbb1962181645a 已优化
