### ISSUE TITLE
用你的模板连接vercel为什么老是出这个错误阿

### ISSUE THREAD

**Issue by iroyway** [forecho/hugo-theme-echo#3]
10:49:55 | Building sites … ERROR 2021/04/25 02:49:55 render of "home" failed: execute of template failed: template: index.html:4:3: executing "index.html" at <partial "head.html" .>: error calling partial: "/vercel/path0/themes/echo/layouts/partials/head.html:54:53": execute of template failed: template: partials/head.html:54:53: executing "partials/head.html" at <resources>: can't evaluate field PostProcess in type interface {}
-- | --
10:49:55 | ERROR 2021/04/25 02:49:55 render of "taxonomyTerm" failed: execute of template failed: template: _default/list.html:4:3: executing "_default/list.html" at <partial "head.html" .>: error calling partial: "/vercel/path0/themes/echo/layouts/partials/head.html:54:53": execute of template failed: template: partials/head.html:54:53: executing "partials/head.html" at <resources>: can't evaluate field PostProcess in type interface {}
10:49:55 | ERROR 2021/04/25 02:49:55 render of "taxonomy" failed: execute of template failed: template: _default/list.html:4:3: executing "_default/list.html" at <partial "head.html" .>: error calling partial: "/vercel/path0/themes/echo/layouts/partials/head.html:54:53": execute of template failed: template: partials/head.html:54:53: executing "partials/head.html" at <resources>: can't evaluate field PostProcess in type interface {}
10:49:55 | ERROR 2021/04/25 02:49:55 render of "taxonomy" failed: execute of template failed: template: _default/list.html:4:3: executing "_default/list.html" at <partial "head.html" .>: error calling partial: "/vercel/path0/themes/echo/layouts/partials/head.html:54:53": execute of template failed: template: partials/head.html:54:53: executing "partials/head.html" at <resources>: can't evaluate field PostProcess in type interface {}

**Comment by forecho** [comment]
是 vercel Hugo 版本原因，使用最新版解决问题。如何使用，请查看：

https://vercel.com/guides/deploying-hugo-with-vercel
