### ISSUE TITLE
表格优化问题

### ISSUE THREAD

**Issue by GeXyu** [forecho/hugo-theme-echo#4]
目前表格边界不清晰，希望增加表格的优化
--------------------------------------------
目前表格效果如下：
![image](https://user-images.githubusercontent.com/17961307/116022828-8789a600-a67d-11eb-970c-661c98d8f2e2.png)

**Comment by zhenghaicaidd01** [comment]
https://github.com/forecho/hugo-theme-echo/commit/5ddcfac33d10c70bb0147dd3b93ff4a0039c4be9

**Comment by forecho** [comment]
https://github.com/forecho/hugo-theme-echo/commit/5ddcfac33d10c70bb0147dd3b93ff4a0039c4be9
